### ISSUE TITLE
[BUG] Prospector==1.7.7 is not compatible with pylint==2.15.7

### ISSUE THREAD

**Issue by barry-jin** [PyCQA/prospector#539]
**Describe the bug** A clear and concise description of what the bug is.

Prospector==1.7.7 will crash if pylint is upgraded to 2.15.7 (works fine with pylint==2.15.6). The stacktrace is like this 
```
$ prospector -X src/
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/prospector/run.py", line 94, in execute
    messages += tool.run(found_files)
  File "/usr/local/lib/python3.8/dist-packages/prospector/tools/pylint/__init__.py", line 253, in run
    self._linter.check(self._args)
  File "/usr/local/lib/python3.8/dist-packages/pylint/lint/pylinter.py", line 696, in check
    ast_per_fileitem = self._get_asts(fileitems, data)
  File "/usr/local/lib/python3.8/dist-packages/pylint/lint/pylinter.py", line 707, in _get_asts
    for fileitem in fileitems:
  File "/usr/local/lib/python3.8/dist-packages/pylint/lint/pylinter.py", line 874, in _iterate_file_descrs
    for descr in self._expand_files(files_or_modules).values():
  File "/usr/local/lib/python3.8/dist-packages/prospector/tools/pylint/linter.py", line 24, in _expand_files
    if self._files.check_module(module["path"]):
TypeError: string indices must be integers
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/bin/prospector", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/prospector/run.py", line 202, in main
    prospector.execute()
  File "/usr/local/lib/python3.8/dist-packages/prospector/run.py", line 112, in execute
    raise FatalProspectorException from ex
TypeError: __init__() missing 1 required positional argument: 'message'
```

**To Reproduce** Steps to reproduce the behavior:

2. Call prospector the following way '....'
3. See error

**Expected behavior** A clear and concise description of what you expected to happen.

**Screenshots** If applicable, add screenshots to help explain your problem.

**Environment (please complete the following information):**

- OS: [e.g. macOS] ubuntu2 0.04
- Tool [e.g. pylint] pylint==2.15.7
- Prospector version [e.g. 1.1.7] prospector==2.15.7
- Python version [e.g. 3.6.8] python==3.8

**Additional context** Add any other context about the problem here. Putting the list of
dependencies installed, e.g. the output of `pip freeze` also helps.

**Comment by Pierre-Sassoulas** [comment]
Duplicate of the bug that was fixed in #530
