### ISSUE TITLE
Prospector fails for `pylint==2.3.0`

### ISSUE THREAD

**Issue by sphuber** [PyCQA/prospector#321]
Due to a recent update of `pylint` to `v2.3.0`, prospector now seems broken. When I run `1.1.5` with `--die-on-tool-error` flag I get the following stack trace:
```
Traceback (most recent call last):
  File "/home/sph/.virtualenvs/aiida_py3/bin/prospector", line 11, in <module>
    sys.exit(main())
  File "/home/sph/.virtualenvs/aiida_py3/lib/python3.6/site-packages/prospector/run.py", line 173, in main
    prospector.execute()
  File "/home/sph/.virtualenvs/aiida_py3/lib/python3.6/site-packages/prospector/run.py", line 66, in execute
    messages += tool.run(found_files)
  File "/home/sph/.virtualenvs/aiida_py3/lib/python3.6/site-packages/prospector/tools/pylint/__init__.py", line 256, in run
    self._linter.check(self._args)
  File "/home/sph/.virtualenvs/aiida_py3/lib/python3.6/site-packages/pylint/lint.py", line 943, in check
    self._do_check(files_or_modules)
  File "/home/sph/.virtualenvs/aiida_py3/lib/python3.6/site-packages/pylint/lint.py", line 1075, in _do_check
    self.check_astroid_module(ast_node, walker, rawcheckers, tokencheckers)
  File "/home/sph/.virtualenvs/aiida_py3/lib/python3.6/site-packages/pylint/lint.py", line 1158, in check_astroid_module
    walker.walk(ast_node)
  File "/home/sph/.virtualenvs/aiida_py3/lib/python3.6/site-packages/pylint/utils.py", line 1303, in walk
    self.walk(child)
  File "/home/sph/.virtualenvs/aiida_py3/lib/python3.6/site-packages/pylint/utils.py", line 1303, in walk
    self.walk(child)
  File "/home/sph/.virtualenvs/aiida_py3/lib/python3.6/site-packages/pylint/utils.py", line 1303, in walk
    self.walk(child)
  File "/home/sph/.virtualenvs/aiida_py3/lib/python3.6/site-packages/pylint/utils.py", line 1300, in walk
    cb(astroid)
  File "/home/sph/.virtualenvs/aiida_py3/lib/python3.6/site-packages/pylint/checkers/refactoring.py", line 485, in visit_if
    self._check_superfluous_else_raise(node)
  File "/home/sph/.virtualenvs/aiida_py3/lib/python3.6/site-packages/pylint/checkers/refactoring.py", line 436, in _check_superfluous_else_raise
    node, msg_id="no-else-raise", returning_node_class=astroid.Raise
  File "/home/sph/.virtualenvs/aiida_py3/lib/python3.6/site-packages/pylint/checkers/refactoring.py", line 426, in _check_superfluous_else
    msg_id, node=node, args="elif" if followed_by_elif else "else"
  File "/home/sph/.virtualenvs/aiida_py3/lib/python3.6/site-packages/pylint/checkers/__init__.py", line 110, in add_message
    self.linter.add_message(msg_id, line, node, args, confidence, col_offset)
  File "/home/sph/.virtualenvs/aiida_py3/lib/python3.6/site-packages/pylint/utils.py", line 496, in add_message
    message_definition, line, node, args, confidence, col_offset
  File "/home/sph/.virtualenvs/aiida_py3/lib/python3.6/site-packages/pylint/utils.py", line 571, in add_one_message
    confidence,
  File "/home/sph/.virtualenvs/aiida_py3/lib/python3.6/site-packages/prospector/tools/pylint/collector.py", line 21, in handle_message
    self.add_message(msg.msg_id, location, msg.msg)
  File "/home/sph/.virtualenvs/aiida_py3/lib/python3.6/site-packages/prospector/tools/pylint/collector.py", line 32, in add_message
    msg_data = self._message_store.get_message_definition(msg_id)
AttributeError: 'MessagesStore' object has no attribute 'get_message_definition'
```

The method `get_message_definition` has indeed been changed to `get_message_definitions` in `pylint==2.3.0`

**Comment by afreepenguin** [comment]
Still getting this 
```
  File "/Users/afree/Desktop/oms8/env2/lib/python3.6/site-packages/prospector/tools/pylint/collector.py", line 21, in handle_message
    self.add_message(msg.msg_id, location, msg.msg)
  File "/Users/afree/Desktop/oms8/env2/lib/python3.6/site-packages/prospector/tools/pylint/collector.py", line 32, in add_message
    msg_data = self._message_store.get_message_definition(msg_id)
AttributeError: 'MessagesStore' object has no attribute 'get_message_definition'
```

```
pylint==2.3.1
pylint-plugin-utils==0.5
prospector==1.1.6.4
```

**Comment by GregHilston** [comment]
Any fix for this yet?

My `requirements.txt`

```
astroid==2.0.4
boto3==1.9.188
botocore==1.12.188
click==6.7
docutils==0.14
dodgy==0.1.9
Flask==0.12
isort==4.3.21
itsdangerous==0.24
Jinja2==2.9.4
jmespath==0.9.4
lazy-object-proxy==1.4.1
MarkupSafe==0.23
mccabe==0.6.1
mypy==0.720
mypy-extensions==0.4.1
pep8-naming==0.4.1
prospector==1.1.6.2
pycodestyle==2.4.0
pydocstyle==4.0.0
pyflakes==1.6.0
pylint==2.1.1
pylint-celery==0.3
pylint-django==2.0.2
pylint-flask==0.5
pylint-plugin-utils==0.5
python-dateutil==2.8.0
python-interface==1.5.1
PyYAML==5.1.1
requirements-detector==0.6
s3transfer==0.2.1
setoptconf==0.2.0
six==1.12.0
snowballstemmer==1.9.0
typed-ast==1.4.0
typing-extensions==3.7.4
urllib3==1.25.3
Werkzeug==0.11.15
wrapt==1.11.2
```

**Comment by chocoelho** [comment]
We should be releasing `1.1.7` anytime soon. Meanwhile, we have pre-release builds `1.1.7.dev1` that works with pylint `2.3.0`

**Comment by chocoelho** [comment]
Closing this as prospector 1.1.7 should fix this issue. Feel free to reopen it if this is erroring for you.
